name: Serverless API Test

on:
  push:
    branches:
      - test
      - staging

jobs:
  start_serverless:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          npm i -g serverless
      - name: Install DynamoDB Local
        run: sls dynamodb install

      - name: Start DynamoDB Local
        run: sls dynamodb start &

      - name: Wait for DynamoDB Local to start
        run: sleep 5    

      - name: Start serverless offline
        run: sls offline start --host=localhost --port=3000

  run_tests:
    needs: start_serverless
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Wait for serverless offline to start
        run: sleep 5

      - name: Run end to end test
        run: npm run e2e:test

      - name: Stop serverless offline
        run: |
          lsof -ti :3000 | xargs kill