name: Serverless API Test

on:
  pull_request:
    branches:
      - test

  push:
    branches:
      - staging

jobs:
  end_two_end-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          npm i -g serverless

      - name: Start serverless offline
        run: sls offline start --host=localhost --port=3000 &

      - name: Wait for serverless offline to start
        run: sleep 5


      - name: Run end to end test
        run:  npm run e2e:test
      - name: Capture serverless offline logs
        run: |
          echo "Serverless offline logs:"
          ps aux | grep serverless

      - name: Stop serverless offline
        run: kill $(lsof -t -i:3000) || true